import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import {useState, useEffect} from 'react';


import styles from '@/styles/Home.module.scss';


// components:
import Header from '@/components/header';
import AddButton from '@/components/addButton';
import SortByComponent from '@/components/sortByComp';
import AddToStock from '@/components/addToStock';



export default function Home() {

  const [sortBy, setSortBy] = useState('price/item');





  return (
    <div className={styles.main}>
      <Head>

        <title>AquaQuacamaya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Header />
      <Link href='/'>Home</Link>

      <div className={styles.topBar}>
      <AddButton />
      <SortByComponent setSortBy={setSortBy} sortBy={sortBy} />
      </div>

      <AddToStock />



    </div>
  )
}
